[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    ui: Запускает все UI автоесты
    smoke: Маркировка для смоук тестов
    regression: Маркировка для регрессионных тестов
    slow: Маркировка для медленных тестов
    critical: Маркировка для критичных тестов
    registration: Маркировка для тестов связанных с регистрацией
    authorization: Маркировка для тестов с авторизацией